name: Ultimate Portfolio Maker
author: Kaustubh Gupta  
description: Updating contrib logs
inputs:
  gh_token:
    description: "Github Personal Access token"
    required: True
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.gh_token }}
